name: deploydocs

# Only run this when the main branch changes, even if docs not directly edited bc they rely on the package
on:
  push:
    branches:
    - main

permissions:
  pages: write      # to deploy to Pages
  id-token: write # Grant id-token: write permission at the workflow level

# This job installs dependencies, build the docs, and pushes it to `gh-pages`
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e . --no-deps --force-reinstall

    # Build the book
    - name: Build the docs
      run: |
        cd docs
        make html

    # create artifact
    - name: Create and upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html


    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 
